trigger: none

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'DeployResources'
    subscriptionId: '619ebd19-9b97-466d-ba19-d85e7ccd4fce'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: './workload/deploy.bicep'
    deploymentMode: 'Incremental'